version: '3.8'
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  backend:
    restart: 'always'
    ports:
      - "8888:8888"
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        JAR_FILE: getir-bookstore.jar
    container_name: "backend"
    depends_on:
      - mongo
